### ISSUE TITLE
合并时错误

### ISSUE THREAD

**Issue by xzyl4303** [Sinryou/ImagesToPDF#1]
![image](https://github.com/user-attachments/assets/f97fd337-6227-4de5-8be4-4a5a81760faf)

**Comment by Sinryou** [comment]
@xzyl4303 你用v1.1.0版本跑吧，v1.1.1和之后的版本有点问题，不知道为啥Lua的dll只能在我的电脑上调起来，目前还没找到解决办法😂
我打算后面出个把逻辑迁移回C#的版本

**Comment by Sinryou** [comment]
@xzyl4303 哥们我刚刚更新了版v1.1.3，拿虚拟机跑了下应该把这个问题解决了，你试下呗
